# Netlifyのビルド設定
[build]
  publish = "/"

# リダイレクト設定
[[redirects]]
  # /blog/slug 形式のURLを index.html に転送し、
  # SPAルーターが処理できるようにするルール
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  # クローラーが /#blog/slug にアクセスした場合のフォールバック
  from = "/*"
  to = "/index.html"
  status = 200
  [redirects.query]
    _escaped_fragment_ = ":splat"