backend:
  name: github
  repo: jleague-big-club/jleague-big-club
  branch: main
media_folder: "img"
public_folder: "/img"
collections:
  - name: "blog"
    label: "ブログ"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "本文", name: "body", widget: "markdown" }
